In [1]:
import pandas as pd

In [10]:
import numpy as np

In [2]:
dataset = pd.read_csv('/databisnis.csv');

In [3]:
dataset

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
41710,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41711,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41712,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41713,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41714,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [4]:
dataset.head(8)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
5,2021,Level 1,99999,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"26,138",ANZSIC06 divisions A-S (excluding classes K633...
6,2021,Level 1,99999,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,"6,991",ANZSIC06 divisions A-S (excluding classes K633...
7,2021,Level 1,99999,All industries,Dollars (millions),H11,Depreciation,Financial performance,"27,801",ANZSIC06 divisions A-S (excluding classes K633...

In [7]:
Year = dataset["Year"]

In [8]:
Year.head(5)

0    2021
1    2021
2    2021
3    2021
4    2021
Name: Year, dtype: int64

In [9]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41715 entries, 0 to 41714
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Year                         41715 non-null  int64
 1   Industry_aggregation_NZSIOC  41715 non-null  object
 2   Industry_code_NZSIOC         41715 non-null  object
 3   Industry_name_NZSIOC         41715 non-null  object
 4   Units                        41715 non-null  object
 5   Variable_code                41715 non-null  object
 6   Variable_name                41715 non-null  object
 7   Variable_category            41715 non-null  object
 8   Value                        41715 non-null  object
 9   Industry_code_ANZSIC06       41715 non-null  object
dtypes: int64(1), object(9)
memory usage: 3.2+ MB

In [11]:
box1 = np.array([1,2,3,4])

In [12]:
box1

array([1, 2, 3, 4])

In [17]:
box2 = np.array([[1,2,3], [4,5,6]])

In [18]:
box2

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])